### ISSUE TITLE
Function galaxy_catalog_analysis_onegal_withuncert_full

### ISSUE THREAD

**Issue by maddycp** [simone-mastrogiovanni/hitchhiker_guide_dark_sirens#4]
Hi there!

I can't seem to find where the functions relating to the OneGal notebook are defined (specifically galaxy_catalog_analysis_onegal_withuncert_full). They're not in the gal4H0.py file or defined in any other notebooks uploaded.

Thank you in advance.

**Comment by simone-mastrogiovanni** [comment]
Hello,

Thanks for flagging the issue. We actually forgot to commit those functions. We have included them with a pull request on the main. Please feel free to reopen the issue if you encounter any problems.

Cheers,

Simone

**Comment by maddycp** [comment]
Thank you so very much for this!

Maddy
